/* String & Racket Finder — background rally. One file, all 70 pages.
 * Built by rally/build_static.py from srf-rally.js + srf-rally-sound.js +
 * srf-rally-view.js. Do not edit this file by hand — edit those and rebuild.
 */
/* ============================================================================
 * SRFRally — gesture-driven tennis rally for a page background.
 *
 * Two pure-ish functions:
 *   SRFRally.classify(gesture)      -> shot descriptor  (what kind of ball)
 *   SRFRally.trajectory(shot, W, H) -> flight sampler    (where it flies)
 *
 * No DOM, no canvas, no audio, no dependencies, ES5 only (var / function),
 * safe to inline into an old-style file. The ONLY mutable state is the
 * side-alternation counter, exposed as SRFRally.state so the caller can read
 * or reset it (a rally needs the two ends to take turns).
 *
 * Screen convention: y grows downward, y = 0 is the top of the viewport,
 * y = H is the court surface. The drawn NET LINE is at y = H * 0.5.
 * Internally the vertical model works in "court height" h, measured UPWARD
 * from the court in units of the viewport height:  h = 1 - y / H.
 * So h = 0 is the court, h = 0.5 is the net line, h = 1 is the top edge.
 * ==========================================================================*/
(function (root) {
  "use strict";

  /* ---------------------------------------------------------------- utils */

  function num(v, fallback) {          // NaN / Infinity / undefined guard
    return (typeof v === "number" && isFinite(v)) ? v : fallback;
  }
  function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }
  function clamp01(v) { return clamp(v, 0, 1); }

  /* =========================================================================
   * 1) classify(g)
   * ======================================================================*/

  /* --- pace curve -------------------------------------------------------
   * Measured reference speeds on real hardware (px of CSS movement per ms):
   *     lazy phone scroll   0.3 - 0.8
   *     normal scroll flick 0.8 - 1.5
   *     brisk swipe         1.5 - 3.0
   *     hard flick          4.0 - 6.0
   * Saturating Hill curve:  pace = s^E / (s^E + PACE_HALF^E)
   * PACE_HALF is literally "the speed that produces pace 0.5".
   * With PACE_HALF = 1.1 px/ms and E = 1.35 the curve returns:
   *     0.3 -> 0.15   0.5 -> 0.26   0.8 -> 0.39   1.5 -> 0.60
   *     3.0 -> 0.80   5.0 -> 0.88   6.0 -> 0.91
   * i.e. a scroll flick lands in the requested 0.35-0.60 band and a hard
   * flick approaches (but never reaches) 1. Verified in the test table.
   * -------------------------------------------------------------------- */
  var PACE_HALF = 1.1;   // px/ms -> pace 0.5
  var PACE_EXP  = 1.35;  // >1 keeps slow drags soft and stretches the top end

  /* --- gesture geometry thresholds (all stated as numbers, not adjectives) */
  var MS_MIN        = 16;   // one 60Hz frame: the shortest interval a browser can
                            //    actually measure. Clamping here stops a bogus
                            //    timestamp (ms = 0) from reporting 1000 px/ms.
  var SPEED_MAX     = 12;   // px/ms; above this the input is a glitch, not a hand
  var SIDE_EPS_PX   = 8;    // |dx| <= 8px  = no horizontal intent -> alternate sides
  var DROP_DIST_PX  = 90;   // a drop shot needs a SHORT gesture: <= 90px total travel
  var DROP_SPEED    = 0.45; // ...AND a slow one: <= 0.45 px/ms (below a lazy scroll)
  var SLICE_RATIO   = -0.25;// dy/dist <= -0.25  (>= 14.5 deg upward) = open face, slice
  var TOP_RATIO     = 0.25; // dy/dist >= +0.25  (>= 14.5 deg downward) = brushed topspin
  var TOP_MIN_SPEED = 0.35; // ...but only with racket-head speed: >= 0.35 px/ms, the
                            //    bottom of the lazy-scroll band. Slower than that and
                            //    a downward drag is just a soft flat push, not a brush.

  /* --- spin magnitudes --------------------------------------------------- */
  var SPIN_FLAT_MAX = 0.20; // "near 0": a flat drive still has a touch of shape
  var SPIN_SHAPE    = 0.70; // how much of |spin| comes from the gesture ANGLE...
  var SPIN_FLOOR    = 0.30; // ...the rest is a floor, so a topspin ball is never flat
  var SPIN_PACE_MIN = 0.45; // at pace 0 the ball still carries 45% of that spin
                            //    (a slow brushed ball spins, just not viciously)
  var SPIN_DROP     = -0.45;// a drop shot is a chopped, floating backspin touch

  /* --- power weights (drives audio loudness) ----------------------------- */
  var POWER_EXP  = 1.15;    // slight perceptual curve: quiet balls stay quiet
  var POWER_GAIN = {        // for a GIVEN pace the flat drive is the loudest sound
    flat:    1.00,          //   clean, deep contact
    topspin: 0.88,          //   brushed contact loses some of the "thock"
    slice:   0.78,          //   glancing, thin contact
    drop:    0.30           //   feathered; also hard-capped below
  };
  var POWER_DROP_CAP = 0.25;// requirement: a drop shot must never exceed 0.25

  /* Side alternation state. Pure-vertical scrolls have no left/right intent,
   * so the two ends of the court take turns and a rally develops instead of
   * one player hitting every ball. Exposed for the caller (and for tests). */
  var state = {
    lastSide: "back",   // side of the previous shot; first vertical scroll -> "fore"
    shots: 0            // how many shots have been classified this session
  };

  function classify(g) {
    g = g || {};

    // --- guards: NaN, missing fields, zero-length gesture, ms <= 0 --------
    var dx = num(g.dx, 0);
    var dy = num(g.dy, 0);
    var ms = num(g.ms, MS_MIN);
    if (ms < MS_MIN) ms = MS_MIN;             // never divide by 0, negative or noise
    var kind = (g.kind === "swipe" || g.kind === "drag" || g.kind === "scroll")
      ? g.kind : "scroll";

    var dist = Math.sqrt(dx * dx + dy * dy);
    if (!isFinite(dist)) dist = 0;
    var speed = clamp(dist / ms, 0, SPEED_MAX);   // px/ms

    // --- pace -------------------------------------------------------------
    var sp = Math.pow(speed, PACE_EXP);
    var pace = clamp01(sp / (sp + Math.pow(PACE_HALF, PACE_EXP)));

    // --- side -------------------------------------------------------------
    var side;
    if (dx > SIDE_EPS_PX)       side = "fore";   // travelling left -> right
    else if (dx < -SIDE_EPS_PX) side = "back";   // travelling right -> left
    else side = (state.lastSide === "fore") ? "back" : "fore";  // alternate
    state.lastSide = side;
    state.shots++;

    // --- type -------------------------------------------------------------
    // vert = dy/dist in [-1, 1]: -1 straight up, +1 straight down, 0 level.
    var vert = dist > 0 ? (dy / dist) : 0;
    var type;
    if (dist <= DROP_DIST_PX && speed <= DROP_SPEED) {
      type = "drop";                                  // short AND slow = touch
    } else if (vert <= SLICE_RATIO) {
      type = "slice";                                 // gesture climbs = open face
    } else if (vert >= TOP_RATIO && speed >= TOP_MIN_SPEED) {
      type = "topspin";                               // brushed down, with pace
    } else {
      type = "flat";                                  // level (or slow-and-level)
    }

    // --- spin -------------------------------------------------------------
    // Two independent factors, multiplied, so spin never out-ranks pace:
    //   angle  — how steeply the hand brushed across the ball (0.30 .. 1.00)
    //   effort — how fast it did so (0.45 at pace 0, 1.00 at pace 1)
    // A steep, fast wrist-flick saturates at |spin| = 1.
    var shape = Math.abs(vert);                       // 0 level .. 1 vertical
    var mag = (SPIN_FLOOR + SPIN_SHAPE * shape) *
              (SPIN_PACE_MIN + (1 - SPIN_PACE_MIN) * pace);
    var spin;
    if (type === "topspin") {
      spin =  clamp(mag, 0.20, 1);
    } else if (type === "slice") {
      spin = -clamp(mag, 0.20, 1);
    } else if (type === "drop") {
      spin = SPIN_DROP;
    } else {
      spin = clamp(vert * SPIN_FLAT_MAX, -SPIN_FLAT_MAX, SPIN_FLAT_MAX);
    }

    // --- power ------------------------------------------------------------
    var power = clamp01(Math.pow(pace, POWER_EXP) * POWER_GAIN[type]);
    if (type === "drop" && power > POWER_DROP_CAP) power = POWER_DROP_CAP;

    return {
      type: type,
      side: side,
      pace: pace,
      spin: spin,
      power: power,
      kind: kind          // echoed back so the caller can tune input handling
    };
  }

  /* =========================================================================
   * 2) trajectory(shot, W, H)
   *
   * THE FLIGHT MODEL (one model, four parameter sets — not four curves)
   * ------------------------------------------------------------------------
   * Time is normalised: tau = 0 at contact, 1 at the end of the flight.
   *
   * HORIZONTAL — constant-drag decay (linear drag, closed form):
   *     v(tau) = v0 * exp(-DRAG_H * tau)
   *     x(tau) = fromX + dir * span * (1 - exp(-DRAG_H*tau)) / (1 - exp(-DRAG_H))
   *   DRAG_H = 0.55 means the ball keeps exp(-0.55) = 58% of its horizontal
   *   speed by the far side: a real tennis ball loses ~40% of its speed
   *   between racket and bounce. x is therefore strictly monotonic and the
   *   ball covers ground faster early, exactly like the real thing.
   *   u(tau) = exp(-DRAG_H*tau) is the normalised horizontal speed, reused by
   *   the Magnus term below.
   *
   * VERTICAL — gravity + Magnus + quadratic air drag, integrated numerically:
   *     h'' = -G  -  G*MAGNUS*spin*u(tau)  -  DRAG_V * h' * |h'|
   *            (a)          (b)                    (c)
   *   (a) gravity. Expressed in screen-heights per tau^2, which is where the
   *       ms^2 comes from: converting 9.81 m/s^2 into normalised time gives
   *       G = g * (ms/1000)^2 / metresPerScreenHeight, i.e. G scales with the
   *       square of the flight time. Consequence, for free: a slow ball
   *       (drop shot) loops steeply, a fast ball flies flat. G_REF is that
   *       whole expression evaluated at the reference flight of 700ms, with
   *       the vertical exaggerated ~4x the way a broadcast Hawk-Eye graphic
   *       exaggerates it — a literal-scale arc would be an invisible 12px.
   *   (b) Magnus, to first order: force perpendicular to velocity, magnitude
   *       proportional to spin rate and to airspeed. With a mostly-horizontal
   *       velocity its vertical component is proportional to the HORIZONTAL
   *       speed u(tau), so it fades as the ball slows. spin > 0 (topspin)
   *       pushes DOWN, spin < 0 (slice) pushes UP. MAGNUS = 0.9 means a fully
   *       spun ball leaves the racket with +/-0.9 g of aerodynamic force,
   *       which is the right order for a heavy ATP topspin ball.
   *   (c) quadratic air resistance on the vertical axis; always opposes
   *       motion, so the climb is shorter than the fall (a real projectile
   *       with drag peaks before mid-flight).
   *
   *   LAUNCH: instead of hard-coding an apex height, the launch velocity is
   *   V = APEX_T[type] * A0, where A0 is the initial total downward
   *   acceleration and APEX_T is where in the flight the shot is meant to
   *   peak. Under constant acceleration the apex is at tau = V/A, so this
   *   makes APEX_T the shot's *shape* knob and lets the height, the descent
   *   steepness and the landing point fall out of the physics:
   *       topspin  APEX_T 0.34 + big A (gravity + Magnus down) -> early apex,
   *                violent descent, lands right at the far contact point;
   *       slice    APEX_T 0.62 + small A (Magnus fights gravity) -> late apex,
   *                shallow floaty descent, still high at the far side;
   *       flat     APEX_T 0.50, A ~ gravity -> symmetric arc;
   *       drop     APEX_T 0.40 with a long ms, so G (ms^2) is huge: a high,
   *                short lob that falls out of the sky just past the net.
   *
   *   BOUNCE: if h reaches 0 before tau = 1 the ball bounces, h' *= -e.
   *   e = 0.52 + 0.14*spin: a topspin ball kicks up, a slice skids low.
   *
   *   AIMING LOOP: after integrating, the shot is checked against the net
   *   line (h must be >= 0.535 as it passes x = W/2) and against the top of
   *   the viewport (apex <= 0.92). If it fails, the launch velocity is nudged
   *   and the flight re-integrated — the ball is simply aimed higher/lower,
   *   which is what a player does. At most 10 nudges, so it always terminates.
   * ======================================================================*/

  var STEPS   = 96;    // integration steps per flight; 96 is smooth to <0.5px
  var DRAG_H  = 0.55;  // horizontal speed decay over the whole flight (~42% lost)
  var DRAG_V  = 0.06;  // quadratic vertical drag; small, tennis balls are light
  var MAGNUS  = 0.90;  // max aerodynamic force as a fraction of g, at |spin| = 1
  var G_REF   = 4.20;  // gravity in screen-heights per tau^2 for a 700ms flight
  var MS_REF  = 700;   // reference flight time the G_REF constant is quoted at

  var H_CONTACT = 0.30;// contact height: 0.30 * H above the court (~waist height
                       // in this stylised side-on framing)
  var NET_H     = 0.50;// the drawn net line, y = H*0.5  ->  h = 0.5
  var NET_CLEAR = 0.035;// margin: pass the net at least 3.5% of H above the line
  var NET_MIN   = NET_H + NET_CLEAR;
  var CEIL_H    = 0.92;// never inside the top 8% of the viewport (text lives there)
  var EDGE      = 0.06;// contact points sit 6% of W outside the viewport, so the
                       // ball enters and leaves rather than popping into existence

  // Flight time. Requirement: fast shots 450-700ms, drop 900-1100ms, never >1400.
  var MS_FAST = 450, MS_SLOW = 700, MS_DROP_FAST = 920, MS_DROP_SLOW = 1100;
  var MS_MAX  = 1400;

  // How far across the page each shot travels, as a fraction of the full
  // crossing. A drop shot dies just past the net instead of reaching the
  // far side; everything else is a full-length rally ball.
  // 0.72 puts the drop's landing at ~0.74*W, i.e. a quarter of the page past
  // the net line at 0.5*W — as short as it can die while still climbing over
  // a net drawn half a viewport high.
  var DEPTH = { flat: 1.00, topspin: 1.00, slice: 1.00, drop: 0.72 };

  // Where in the flight each shot is meant to peak (the shape knob).
  var APEX_T = { flat: 0.50, topspin: 0.34, slice: 0.62, drop: 0.40 };

  var DENOM = 1 - Math.exp(-DRAG_H);   // normaliser for the horizontal easing

  function easeX(tau) {                // 0..1, monotonic, fast early (drag)
    return (1 - Math.exp(-DRAG_H * tau)) / DENOM;
  }
  function tauAtX(frac) {              // inverse of easeX, for the net crossing
    var q = 1 - frac * DENOM;
    if (q <= 1e-6) return 1;
    return clamp01(-Math.log(q) / DRAG_H);
  }

  /* Integrate the vertical model once. Returns the sampled height profile. */
  function flyVertical(V, G, spin, rest) {
    var dt = 1 / STEPS;
    var h = H_CONTACT, hp = V;
    var out = new Array(STEPS + 1);
    var apexH = h, apexT = 0;
    var i, tau, u, a;
    out[0] = h;
    for (i = 1; i <= STEPS; i++) {
      tau = (i - 1) * dt;
      u = Math.exp(-DRAG_H * tau);                 // normalised horizontal speed
      a = -G                                       // (a) gravity
          - G * MAGNUS * spin * u                  // (b) Magnus, ~ spin * airspeed
          - DRAG_V * hp * Math.abs(hp);            // (c) quadratic air drag
      hp += a * dt;                                // semi-implicit Euler: stable
      h  += hp * dt;
      if (h <= 0) { h = 0; hp = Math.abs(hp) * rest; }   // bounce off the court
      if (h > apexH) { apexH = h; apexT = i * dt; }
      out[i] = h;
    }
    return { h: out, apexH: apexH, apexT: apexT };
  }

  function trajectory(shot, W, H) {
    shot = shot || {};
    W = num(W, 1280); if (W <= 0) W = 1280;
    H = num(H, 720);  if (H <= 0) H = 720;

    var type = DEPTH.hasOwnProperty(shot.type) ? shot.type : "flat";
    var side = (shot.side === "back") ? "back" : "fore";
    var pace = clamp01(num(shot.pace, 0.5));
    var spin = clamp(num(shot.spin, 0), -1, 1);

    // --- flight time ------------------------------------------------------
    var ms = (type === "drop")
      ? MS_DROP_SLOW - (MS_DROP_SLOW - MS_DROP_FAST) * pace   // 1100 -> 920
      : MS_SLOW      - (MS_SLOW      - MS_FAST     ) * pace;  //  700 -> 450
    ms = clamp(ms, 200, MS_MAX);

    // --- horizontal geometry ---------------------------------------------
    var dir  = (side === "back") ? -1 : 1;                  // +1 = left to right
    var span = W * (1 + 2 * EDGE) * DEPTH[type];
    var fromX = (dir > 0) ? -EDGE * W : W + EDGE * W;
    var toX   = fromX + dir * span;

    // tau at which the ball passes the net (x = W/2)
    var netFrac = ((W * 0.5) - fromX) / (dir * span);
    var tauNet  = (netFrac > 0 && netFrac < 1) ? tauAtX(netFrac) : 0.5;

    // --- vertical model ---------------------------------------------------
    // gravity scales with ms^2 (real g rewritten in normalised time)
    var G = G_REF * (ms / MS_REF) * (ms / MS_REF);
    // initial total downward acceleration, used to aim the launch
    var A0 = G * (1 + MAGNUS * spin);
    if (A0 < 0.15 * G) A0 = 0.15 * G;          // a fully sliced ball still falls
    var V = APEX_T[type] * A0;                 // apex ~ at APEX_T of the flight
    var rest = clamp(0.52 + 0.14 * spin, 0.35, 0.72);  // topspin kicks, slice skids

    // aiming loop: clear the net, stay inside the viewport
    var fly = flyVertical(V, G, spin, rest), guard = 0;
    var iNet = Math.round(tauNet * STEPS);
    while (guard++ < 10) {
      if (fly.h[iNet] < NET_MIN)      V *= 1.10;   // aim higher
      else if (fly.apexH > CEIL_H)    V *= 0.93;   // aim flatter
      else break;
      fly = flyVertical(V, G, spin, rest);
    }

    var hs = fly.h;

    function sample(t) {
      t = clamp01(num(t, 0));
      var f = t * STEPS;
      var i = Math.floor(f);
      if (i >= STEPS) i = STEPS - 1;
      var frac = f - i;
      var h = hs[i] + (hs[i + 1] - hs[i]) * frac;
      h = clamp01(h);                       // never above the viewport / below court
      return {
        x: fromX + dir * span * easeX(t),
        y: H * (1 - h),
        z: h                                // 0 = on the court, 1 = top of viewport
      };
    }

    return {
      from: { x: fromX, y: H * (1 - H_CONTACT) },
      to:   { x: toX,   y: H * (1 - clamp01(hs[STEPS])) },
      ms: ms,
      apex: fly.apexH * H,                  // px ABOVE THE COURT at the peak
      apexY: H * (1 - fly.apexH),           // ...same point as a screen y, in px
      apexT: fly.apexT,                     // ...and when it happens, t in 0..1
      netT: tauNet,                         // t at which x crosses W/2
      netY: H * (1 - clamp01(hs[iNet])),    // screen y as it passes the net line
      sample: sample
    };
  }

  root.SRFRally = {
    classify: classify,
    trajectory: trajectory,
    state: state          // { lastSide, shots } — the documented side alternation
  };

})(typeof window !== "undefined" ? window : this);

/* SRFRallySound — synthesised tennis impacts, Web Audio, no assets, ES5.
 * One AudioContext (lazy), one shared noise buffer, per-hit nodes self-destruct.
 * Peak amplitude is hard-clamped well under 0.16.
 */
(function (global) {
  'use strict';

  var PEAK_CEIL   = 0.155;  /* absolute clamp on summed per-hit peak */
  var MAX_PAN     = 0.35;
  var MAX_VOICES  = 16;     /* runaway guard: never reached by a real rally */
  var NOISE_SECS  = 1.0;
  var FLOOR       = 0.0001; /* exponential ramps cannot touch zero */

  var ctx      = null;
  var master   = null;
  var noiseBuf = null;
  var dead     = false;     /* audio unavailable -> permanent silence */
  var voices   = 0;

  function rnd(a, b) { return a + Math.random() * (b - a); }
  function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }
  function unit(v, d) {
    return (typeof v === 'number' && isFinite(v)) ? clamp(v, 0, 1) : d;
  }

  /* ---------------------------------------------------------------- setup */

  function makeNoise(c) {
    var len = Math.floor(c.sampleRate * NOISE_SECS);
    var buf = c.createBuffer(1, len, c.sampleRate);
    var d = buf.getChannelData(0);
    var last = 0, i, w;
    for (i = 0; i < len; i++) {
      w = Math.random() * 2 - 1;
      /* very light smoothing: pure white is harsher than a real impact */
      last = 0.82 * w + 0.18 * last;
      d[i] = last;
    }
    return buf;
  }

  function init() {
    if (dead || ctx) { return ctx; }
    try {
      var AC = global.AudioContext || global.webkitAudioContext;
      if (!AC) { dead = true; return null; }
      ctx = new AC();
      master = ctx.createGain();
      master.gain.value = 1;
      master.connect(ctx.destination);
      noiseBuf = makeNoise(ctx);
    } catch (e) {
      dead = true; ctx = null; master = null; noiseBuf = null;
    }
    return ctx;
  }

  function ready() {
    if (!api.enabled || dead) { return false; }
    if (!ctx) { init(); }
    if (!ctx || !master || !noiseBuf) { return false; }
    /* suspended / interrupted / closed: play nothing, queue nothing */
    if (ctx.state !== 'running') { return false; }
    return voices < MAX_VOICES;
  }

  function unlock() {
    try {
      if (!ctx) { init(); }
      if (ctx && ctx.state === 'suspended' && ctx.resume) { ctx.resume(); }
    } catch (e) { /* ignore */ }
  }

  /* ------------------------------------------------------------- voicings */

  /* pace/power are 0..1. Returns the full recipe for one impact. */
  function recipe(type, pace, power, isBounce) {
    var s;
    if (isBounce) {
      s = { flt: 'lowpass',  freq: 250 + pace * 200, q: 0.7,  hp: 0,
            noise: 0.055, tone: 0.010, toneHz: 150 + pace * 70, toneWave: 'sine',
            attack: 0.0040, dur: 0.130, sweep: 0.70, rate: 0.80 };
    } else if (type === 'topspin') {
      /* duller + longer than flat, more string brush, small downward sweep */
      s = { flt: 'bandpass', freq: 1400 + pace * 500, q: 1.25, hp: 250,
            noise: 0.100, tone: 0.018, toneHz: 520 + pace * 150, toneWave: 'triangle',
            attack: 0.0018, dur: 0.095, sweep: 0.55, rate: 0.97 };
    } else if (type === 'slice') {
      /* thin, chopped: narrow high band, little body, quieter, sharp decay */
      s = { flt: 'bandpass', freq: 2600 + pace * 600, q: 6.5, hp: 1300,
            noise: 0.082, tone: 0.012, toneHz: 1150 + pace * 250, toneWave: 'triangle',
            attack: 0.0010, dur: 0.045, sweep: 0.88, rate: 1.06 };
    } else if (type === 'drop') {
      /* soft, muffled, almost no tail — clearly gentler than everything else */
      s = { flt: 'lowpass',  freq: 700 + pace * 200, q: 0.7,  hp: 0,
            noise: 0.040, tone: 0.006, toneHz: 300 + pace * 60, toneWave: 'sine',
            attack: 0.0025, dur: 0.038, sweep: 0.80, rate: 0.90 };
    } else { /* flat: loudest, brightest, shortest — a hard crack */
      s = { flt: 'bandpass', freq: 2200 + pace * 800, q: 0.9,  hp: 500,
            noise: 0.115, tone: 0.030, toneHz: 820 + pace * 220, toneWave: 'triangle',
            attack: 0.0012, dur: 0.055, sweep: 0.75, rate: 1.00 };
    }

    /* loudness follows power, with a floor so a soft shot is still audible */
    var lvl = 0.35 + 0.65 * power;
    /* a few percent of jitter so a rally is not a machine gun */
    var jit = rnd(0.96, 1.04);
    s.noise *= lvl * jit;
    s.tone  *= lvl * jit;
    s.freq  *= rnd(0.97, 1.03);
    s.toneHz *= rnd(0.97, 1.03);
    s.dur   *= rnd(0.94, 1.06);
    s.rate  *= rnd(0.96, 1.04);

    /* hard ceiling on the summed peak of the two parallel branches */
    var sum = s.noise + s.tone;
    if (sum > PEAK_CEIL) {
      var k = PEAK_CEIL / sum;
      s.noise *= k; s.tone *= k;
    }
    return s;
  }

  function env(param, t0, peak, attack, dur) {
    param.setValueAtTime(FLOOR, t0);
    param.exponentialRampToValueAtTime(Math.max(peak, FLOOR * 2), t0 + attack);
    param.exponentialRampToValueAtTime(FLOOR, t0 + dur);
    param.setValueAtTime(0, t0 + dur + 0.001);
  }

  /* ------------------------------------------------------------- the voice */

  function play(s, pan) {
    var nodes = [];
    var srcs  = [];
    var done  = false;
    var pending = 0;
    var timer = null;

    function keep(n) { nodes.push(n); return n; }

    function cleanup() {
      if (done) { return; }
      done = true;
      if (timer !== null && global.clearTimeout) { global.clearTimeout(timer); }
      timer = null;
      for (var i = 0; i < nodes.length; i++) {
        try { nodes[i].onended = null; } catch (e1) { /* not a source */ }
        try { nodes[i].disconnect(); } catch (e2) { /* already gone */ }
      }
      nodes.length = 0; srcs.length = 0;
      voices--;
    }

    function ended() { pending--; if (pending <= 0) { cleanup(); } }

    voices++;
    try {
      var t0   = ctx.currentTime;
      var stop = t0 + s.dur + 0.02;

      var out = master;
      if (ctx.createStereoPanner) {
        var p = keep(ctx.createStereoPanner());
        p.pan.value = clamp(pan, -MAX_PAN, MAX_PAN);
        p.connect(master);
        out = p;
      }

      /* --- noise branch: source -> [highpass] -> band/low-pass -> gain */
      var ng = keep(ctx.createGain());
      ng.connect(out);
      env(ng.gain, t0, s.noise, s.attack, s.dur);

      var flt = keep(ctx.createBiquadFilter());
      flt.type = s.flt;
      flt.frequency.setValueAtTime(s.freq, t0);
      if (s.sweep < 1) {
        flt.frequency.exponentialRampToValueAtTime(s.freq * s.sweep, t0 + s.dur);
      }
      flt.Q.value = s.q;
      flt.connect(ng);

      var head = flt;
      if (s.hp > 0) {
        var hp = keep(ctx.createBiquadFilter());
        hp.type = 'highpass';
        hp.frequency.value = s.hp;
        hp.Q.value = 0.7;           /* Butterworth: no resonant boost */
        hp.connect(flt);
        head = hp;
      }

      var src = keep(ctx.createBufferSource());
      src.buffer = noiseBuf;        /* the ONE shared buffer */
      src.playbackRate.value = s.rate;
      src.connect(head);
      srcs.push(src);

      /* --- tonal branch: frame/string ping, always well below the noise */
      var tg = keep(ctx.createGain());
      tg.connect(out);
      env(tg.gain, t0, s.tone, s.attack + 0.001, s.dur * 0.85);

      var osc = keep(ctx.createOscillator());
      osc.type = s.toneWave;
      osc.frequency.setValueAtTime(s.toneHz, t0);
      osc.frequency.exponentialRampToValueAtTime(
        s.toneHz * (0.6 + 0.35 * s.sweep), t0 + s.dur * 0.85);
      osc.connect(tg);
      srcs.push(osc);

      pending = srcs.length;
      for (var i = 0; i < srcs.length; i++) {
        srcs[i].onended = ended;
      }
      /* read a random slice of the shared buffer so repeats do not phase-lock */
      src.start(t0, rnd(0, NOISE_SECS * 0.5));
      src.stop(stop);
      osc.start(t0);
      osc.stop(t0 + s.dur * 0.85 + 0.01);

      /* belt and braces: some engines drop onended, so force a sweep later */
      if (global.setTimeout) {
        timer = global.setTimeout(cleanup, (s.dur + 0.25) * 1000);
      }
    } catch (e) {
      cleanup();
    }
  }

  /* ----------------------------------------------------------------- API */

  var api = {
    enabled: true,

    init: function () { init(); return api; },

    unlock: function () { unlock(); return api; },

    setEnabled: function (on) {
      api.enabled = !!on;
      return api;
    },

    hit: function (shot) {
      if (!api.enabled) { return; }        /* create NOTHING */
      if (!ready()) { return; }
      try {
        shot = shot || {};
        var pace  = unit(shot.pace, 0.6);
        var power = unit(shot.power, 0.6);
        var s = recipe(shot.type, pace, power, false);
        var pan = (shot.side === 'back' ? -1 : 1) * rnd(0.16, MAX_PAN);
        play(s, pan);
      } catch (e) { /* silence beats a thrown error */ }
    },

    bounce: function (power) {
      if (!api.enabled) { return; }
      if (!ready()) { return; }
      try {
        var p = unit(power, 0.5);
        var s = recipe(null, p, p, true);
        play(s, rnd(-0.12, 0.12));
      } catch (e) { /* ignore */ }
    }
  };

  global.SRFRallySound = api;

})(typeof window !== 'undefined' ? window
   : (typeof globalThis !== 'undefined' ? globalThis : this));

/* ============================================================================
 * SRFRallyView — the background rally: gesture capture, canvas, loop discipline.
 *
 * Sits on top of SRFRally (physics) and SRFRallySound (audio). Draws a tennis
 * ball rallying across the page behind the content, in the live theme accent at
 * low alpha, with a single net line.
 *
 * THE RULE THIS FILE EXISTS TO KEEP: requestAnimationFrame runs ONLY while a
 * ball is in the air. Idle costs zero frames. b149 spent a whole session taking
 * 1.4 s of needless work off this page's boot; a background animation that
 * ticks forever would hand it straight back.
 *
 * ES5, no dependencies, no DOM outside its own canvas.
 * ==========================================================================*/
(function (W) {
  "use strict";

  var CFG = {
    treatment: "trace",     // "trace" | "court" | "spin"
    alpha: 0.42,            // master opacity of everything drawn — "not 100%"
    netAlpha: 0.16,
    trail: 26,              // trail samples kept
    ballR: 7,               // ball radius in CSS px at z = 0 (court level)
    zGrow: 0.55,            // how much bigger the ball gets at the top of its arc
    maxLive: 3,             // balls allowed in the air at once
    minGapMs: 90,           // ignore gestures closer together than this
    idleHintMs: 0           // 0 = no idle serve; >0 = auto-rally every N ms
  };

  var onShot = null;        // optional observer, set via api.onShot()
  var cv = null, cx = null, dpr = 1, VW = 0, VH = 0;
  var live = [];            // balls in flight
  /* lastHit starts at -1e9, NOT 0. now() is performance.now(), so 0 is a real
     timestamp — the page's own navigation start. With lastHit = 0 the very
     first shot of a page is gated by minGapMs whenever the module is ready
     within 90 ms of navigation, which the static pages manage easily (they
     reach DOMContentLoaded in 14-21 ms). Measured: serve() returned null at
     performance.now() = 87. */
  var raf = 0, lastHit = -1e9, running = false, reduced = false;
  var accent = "rgb(158,186,171)";
  var host = null;

  /* ------------------------------------------------------------ utilities */

  function now() { return (W.performance && W.performance.now) ? W.performance.now() : Date.now(); }

  function readAccent() {
    try {
      var cs = getComputedStyle(document.documentElement);
      var v = (cs.getPropertyValue("--magenta-fg") || cs.getPropertyValue("--magenta")
               || cs.getPropertyValue("--accent") || "").trim();
      if (v) { accent = v; }
    } catch (e) { /* keep the default */ }
  }

  /* Parse any CSS colour into "r,g,b" so we can apply our own alpha. Uses the
   * canvas itself as the parser, which handles hex, rgb(), hsl() and colour
   * names without a regex zoo. */
  function rgbOf(col) {
    try {
      var c = document.createElement("canvas").getContext("2d");
      c.fillStyle = "#000"; c.fillStyle = col;
      var s = c.fillStyle;                       // normalised to #rrggbb or rgba()
      if (s.charAt(0) === "#") {
        return parseInt(s.substr(1, 2), 16) + "," +
               parseInt(s.substr(3, 2), 16) + "," +
               parseInt(s.substr(5, 2), 16);
      }
      var m = s.match(/(\d+)[,\s]+(\d+)[,\s]+(\d+)/);
      return m ? (m[1] + "," + m[2] + "," + m[3]) : "158,186,171";
    } catch (e) { return "158,186,171"; }
  }
  var accentRGB = "158,186,171";

  /* The BALL is always optic yellow, whatever the theme accent is. A tennis ball
     is optic yellow — that is the one colour on the page that is not a palette
     choice, so it does not follow --magenta. The net line still does: the net is
     court furniture and belongs to the theme, the ball belongs to the sport. */
  var BALL = "217,234,85";                    // #D9EA55, the a3 / opticA yellow

  /* ---------------------------------------------------------------- canvas */

  function size() {
    if (!cv) { return; }
    dpr = Math.min(W.devicePixelRatio || 1, 2);   // cap at 2: a 3x phone canvas
    VW = cv.clientWidth || W.innerWidth;          // costs 2.25x the fill for no
    VH = cv.clientHeight || W.innerHeight;        // visible gain on a soft trail
    cv.width = Math.round(VW * dpr);
    cv.height = Math.round(VH * dpr);
    cx.setTransform(dpr, 0, 0, dpr, 0, 0);
  }

  function mount(parent) {
    if (cv) { return; }
    host = parent || document.body;
    cv = document.createElement("canvas");
    cv.className = "srfRallyCv";
    cv.setAttribute("aria-hidden", "true");
    cv.style.cssText = "position:fixed;inset:0;width:100%;height:100%;" +
      "pointer-events:none;z-index:1;display:block;mix-blend-mode:screen;";
    cx = cv.getContext("2d");
    host.appendChild(cv);
    size();
    W.addEventListener("resize", size, { passive: true });
    readAccent();
    accentRGB = rgbOf(accent);
  }

  /* ------------------------------------------------------------- the shot */

  function serve(g) {
    if (reduced || !cv) { return null; }
    var t = now();
    if (t - lastHit < CFG.minGapMs) { return null; }
    if (live.length >= CFG.maxLive) { return null; }
    lastHit = t;

    var shot = W.SRFRally.classify(g);
    var tr = W.SRFRally.trajectory(shot, VW, VH);
    live.push({ shot: shot, tr: tr, t0: t, trail: [], bounced: false });

    if (W.SRFRallySound) { W.SRFRallySound.hit(shot); }
    start();
    if (onShot) { try { onShot(shot, tr); } catch (e) { /* a listener must not
      be able to break the rally */ } }
    return shot;
  }

  /* ------------------------------------------------------------- the loop */

  function start() {
    if (running) { return; }
    running = true;
    raf = W.requestAnimationFrame(frame);
  }

  function stop() {
    running = false;
    if (raf) { W.cancelAnimationFrame(raf); raf = 0; }
    if (cx) { cx.clearRect(0, 0, VW, VH); }
  }

  function frame() {
    var t = now(), i, b, p, u;
    cx.clearRect(0, 0, VW, VH);
    drawNet();

    for (i = live.length - 1; i >= 0; i--) {
      b = live[i];
      u = (t - b.t0) / b.tr.ms;
      if (u >= 1) { live.splice(i, 1); continue; }
      p = b.tr.sample(u);

      b.trail.push(p);
      if (b.trail.length > CFG.trail) { b.trail.shift(); }

      /* the bounce is a sound event, fired once, when the ball reaches the court */
      if (!b.bounced && p.z <= 0.02 && u > 0.2) {
        b.bounced = true;
        if (W.SRFRallySound) { W.SRFRallySound.bounce(b.shot.power * 0.7); }
      }
      drawBall(b, p, u);
    }

    if (live.length) { raf = W.requestAnimationFrame(frame); }
    else { stop(); }          /* NOTHING in the air -> no rAF at all */
  }

  /* ------------------------------------------------------------- painting */

  function drawNet() {
    if (CFG.netAlpha <= 0) { return; }
    var y = Math.round(VH * 0.5) + 0.5;
    var g = cx.createLinearGradient(0, 0, VW, 0);
    g.addColorStop(0,    "rgba(" + accentRGB + ",0)");
    g.addColorStop(0.5,  "rgba(" + accentRGB + "," + (CFG.netAlpha * CFG.alpha).toFixed(3) + ")");
    g.addColorStop(1,    "rgba(" + accentRGB + ",0)");
    cx.strokeStyle = g;
    cx.lineWidth = 1;
    cx.beginPath(); cx.moveTo(0, y); cx.lineTo(VW, y); cx.stroke();
  }

  function drawBall(b, p, u) {
    var A = CFG.alpha;
    var n = b.trail.length, i, q, f, r;
    var fade = u > 0.86 ? (1 - u) / 0.14 : 1;          // ease out at the end
    var spin = b.shot.spin;

    /* --- trail ---------------------------------------------------------- */
    if (CFG.treatment === "spin") {
      /* width and colour carry the spin: a topspin ball drags a heavier,
         warmer wake, a slice a thin cold one */
      for (i = 1; i < n; i++) {
        q = b.trail[i]; f = i / n;
        cx.strokeStyle = "rgba(" + BALL + "," + (A * 0.30 * f * f * fade).toFixed(3) + ")";
        cx.lineWidth = (0.6 + 2.2 * f * (0.55 + 0.45 * Math.abs(spin)));
        cx.beginPath();
        cx.moveTo(b.trail[i - 1].x, b.trail[i - 1].y);
        cx.lineTo(q.x, q.y);
        cx.stroke();
      }
    } else {
      cx.lineWidth = 1.6;
      for (i = 1; i < n; i++) {
        q = b.trail[i]; f = i / n;
        cx.strokeStyle = "rgba(" + BALL + "," + (A * 0.26 * f * f * fade).toFixed(3) + ")";
        cx.beginPath();
        cx.moveTo(b.trail[i - 1].x, b.trail[i - 1].y);
        cx.lineTo(q.x, q.y);
        cx.stroke();
      }
    }

    /* --- ground shadow, "court" treatment only -------------------------- */
    if (CFG.treatment === "court") {
      var sy = VH * 0.92;                              // a notional court line
      var sw = 10 * (1 - p.z * 0.55);
      cx.fillStyle = "rgba(" + BALL + "," + (A * 0.10 * (1 - p.z) * fade).toFixed(3) + ")";
      cx.beginPath();
      cx.ellipse(p.x, sy, Math.max(2, sw), Math.max(1, sw * 0.28), 0, 0, 6.2832);
      cx.fill();
    }

    /* --- the ball ------------------------------------------------------- */
    r = CFG.ballR * (1 + CFG.zGrow * p.z);
    var core = A * (0.55 + 0.35 * b.shot.pace) * fade;

    var g = cx.createRadialGradient(p.x, p.y, 0, p.x, p.y, r * 2.4);
    g.addColorStop(0, "rgba(" + BALL + "," + core.toFixed(3) + ")");
    g.addColorStop(0.45, "rgba(" + BALL + "," + (core * 0.35).toFixed(3) + ")");
    g.addColorStop(1, "rgba(" + BALL + ",0)");
    cx.fillStyle = g;
    cx.beginPath(); cx.arc(p.x, p.y, r * 2.4, 0, 6.2832); cx.fill();

    cx.fillStyle = "rgba(" + BALL + "," + Math.min(1, core * 1.25).toFixed(3) + ")";
    cx.beginPath(); cx.arc(p.x, p.y, r * 0.55, 0, 6.2832); cx.fill();

    /* --- spin ring, "spin" treatment only -------------------------------- */
    if (CFG.treatment === "spin" && Math.abs(spin) > 0.25) {
      var rot = u * b.tr.ms * 0.02 * (spin > 0 ? 1 : -1);
      cx.strokeStyle = "rgba(" + BALL + "," + (A * 0.22 * Math.abs(spin) * fade).toFixed(3) + ")";
      cx.lineWidth = 1;
      cx.beginPath();
      cx.arc(p.x, p.y, r * 1.5, rot, rot + 2.4);
      cx.stroke();
    }
  }

  /* ------------------------------------------------------- gesture capture
   * Three sources, one shape: {dx, dy, ms, kind}.
   *  - touch: real swipe, measured start to end
   *  - mouse: press-drag-release
   *  - wheel/scroll: accumulated inside a short window, flushed when it stops
   * Everything is passive so nothing here can block scrolling.
   * -------------------------------------------------------------------- */

  var tStart = null, mDown = null;
  var wDX = 0, wDY = 0, wT0 = 0, wTimer = 0;
  var WHEEL_FLUSH = 90;       // ms of quiet that ends a scroll burst

  function onTouchStart(e) {
    var t = e.touches && e.touches[0]; if (!t) { return; }
    tStart = { x: t.clientX, y: t.clientY, t: now() };
    unlockAudio();
  }
  function onTouchEnd(e) {
    if (!tStart) { return; }
    var t = (e.changedTouches && e.changedTouches[0]); if (!t) { tStart = null; return; }
    serve({ dx: t.clientX - tStart.x, dy: t.clientY - tStart.y,
            ms: now() - tStart.t, kind: "swipe" });
    tStart = null;
  }
  function onDown(e) { mDown = { x: e.clientX, y: e.clientY, t: now() }; unlockAudio(); }
  function onUp(e) {
    if (!mDown) { return; }
    var dx = e.clientX - mDown.x, dy = e.clientY - mDown.y;
    if (Math.abs(dx) + Math.abs(dy) > 12) {          // a click is not a shot
      serve({ dx: dx, dy: dy, ms: now() - mDown.t, kind: "drag" });
    }
    mDown = null;
  }
  function onWheel(e) {
    if (!wT0) { wT0 = now(); wDX = 0; wDY = 0; }
    wDX += e.deltaX || 0;
    wDY += e.deltaY || 0;
    if (wTimer) { clearTimeout(wTimer); }
    wTimer = setTimeout(flushWheel, WHEEL_FLUSH);
  }
  function flushWheel() {
    wTimer = 0;
    if (!wT0) { return; }
    var ms = now() - wT0;
    /* deltaY in "lines" (deltaMode 1) is ~16x smaller than pixels; the browser
       already normalises most of it, and over-correcting turned every trackpad
       nudge into a smash. Left as raw px, which is what deltaMode 0 gives. */
    if (Math.abs(wDX) + Math.abs(wDY) > 24) {
      serve({ dx: wDX, dy: wDY, ms: ms, kind: "scroll" });
    }
    wT0 = 0; wDX = 0; wDY = 0;
  }

  /* --------------------------------------------------------------- audio */

  var SND_KEY = "srf:rallysound";
  var unlocked = false;

  function unlockAudio() {
    if (unlocked || !W.SRFRallySound) { return; }
    unlocked = true;
    try { W.SRFRallySound.unlock(); } catch (e) { /* ignore */ }
  }

  function soundOn() {
    try { return localStorage.getItem(SND_KEY) === "1"; } catch (e) { return false; }
  }
  function setSound(on) {
    try { localStorage.setItem(SND_KEY, on ? "1" : "0"); } catch (e) { /* ignore */ }
    if (W.SRFRallySound) { W.SRFRallySound.setEnabled(!!on); if (on) { unlockAudio(); } }
  }

  /* ----------------------------------------------------------------- API */

  var api = {
    cfg: CFG,

    start: function (parent) {
      try {
        reduced = W.matchMedia && W.matchMedia("(prefers-reduced-motion: reduce)").matches;
      } catch (e) { reduced = false; }
      if (reduced) { return api; }               // honour the OS setting, silently
      mount(parent);
      if (W.SRFRallySound) { W.SRFRallySound.setEnabled(soundOn()); }

      document.addEventListener("touchstart", onTouchStart, { passive: true });
      document.addEventListener("touchend", onTouchEnd, { passive: true });
      document.addEventListener("mousedown", onDown, { passive: true });
      document.addEventListener("mouseup", onUp, { passive: true });
      W.addEventListener("wheel", onWheel, { passive: true });
      return api;
    },

    /* called when the reader leaves the landing page: kill the loop, drop the
       listeners, clear the canvas. Nothing keeps ticking behind the benches. */
    stop: function () {
      live.length = 0;
      stop();
      document.removeEventListener("touchstart", onTouchStart);
      document.removeEventListener("touchend", onTouchEnd);
      document.removeEventListener("mousedown", onDown);
      document.removeEventListener("mouseup", onUp);
      W.removeEventListener("wheel", onWheel);
      if (cv && cv.parentNode) { cv.parentNode.removeChild(cv); cv = null; cx = null; }
      return api;
    },

    serve: serve,
    onShot: function (fn) { onShot = (typeof fn === "function") ? fn : null; return api; },
    setTreatment: function (t) { CFG.treatment = t; return api; },
    setBall: function (rgb) { BALL = rgb || BALL; return api; },   // "r,g,b"
    setAlpha: function (a) { CFG.alpha = a; return api; },
    soundOn: soundOn,
    setSound: setSound,
    repaintAccent: function () { readAccent(); accentRGB = rgbOf(accent); return api; },
    live: function () { return live.length; },
    isRunning: function () { return running; }
  };

  W.SRFRallyView = api;

})(typeof window !== "undefined" ? window : this);


/* ============================================================================
 * The page policy. The three modules above know nothing about this site;
 * everything site-specific lives here, and ONE file serves two very different
 * kinds of page:
 *
 *   the APP (index.html)  - four modes in one document. The rally belongs to
 *                           the LANDING page only: the benches are working
 *                           surfaces, their score cells carry an OKLCH heat
 *                           ramp where the colour IS the data, and their
 *                           sliders are drag targets (a measured drag on a
 *                           weight slider serves a ball). Detected by the
 *                           control the app carries in its gear panel.
 *   a STATIC page         - one column of prose and plain tables, no modes, no
 *                           heat map, no drag targets. The whole page is the
 *                           court, and the control is injected into the footer
 *                           so a visitor arriving from a search result can turn
 *                           it off without going to the homepage first.
 *
 * Both share the key `srf:rally` (off | silent | sound), so the choice follows
 * the reader across the whole site.
 * ==========================================================================*/
(function(){
  "use strict";
  var V = window.SRFRallyView;
  if (!V) { return; }

  var KEY = "srf:rally";          /* "off" | "silent" | "sound" */
  var DEF = "silent";             /* the ball plays; the sound does not */
  var mounted = false;
  var foot = null;

  /* the app carries its own control in the gear panel; a static page does not */
  var APP = !!document.getElementById("rallySeg");

  function get(){
    try {
      var v = localStorage.getItem(KEY);
      return (v === "off" || v === "silent" || v === "sound") ? v : DEF;
    } catch(e){ return DEF; }
  }
  function put(v){ try { localStorage.setItem(KEY, v); } catch(e){} }

  /* Where the rally is allowed to run. In the app: the landing page only.
     On a static page: everywhere, because there is only one surface. */
  function onSurface(){
    return APP ? document.body.classList.contains("mode-landing") : true;
  }

  function sync(){
    var want = (get() !== "off") && onSurface();
    if (want && !mounted){ V.start(); mounted = true; }
    else if (!want && mounted){ V.stop(); mounted = false; }
    if (mounted){ V.setSound(get() === "sound"); }
    else if (window.SRFRallySound){ window.SRFRallySound.setEnabled(false); }
  }

  /* ---- the app's control, in the gear panel ------------------------------ */
  function paintSeg(){
    var seg = document.getElementById("rallySeg"); if (!seg) { return; }
    var cur = get(), bs = seg.querySelectorAll("button[data-rl]"), i;
    for (i = 0; i < bs.length; i++){
      bs[i].setAttribute("aria-pressed", String(bs[i].getAttribute("data-rl") === cur));
    }
  }

  /* ---- a static page's control, injected into the footer -----------------
     One quiet line of type, no boxes: muted at rest, the live state in the
     accent. A visitor who lands here from Google can switch it off without
     first finding the homepage. */
  function buildFoot(){
    var f = document.querySelector("footer"); if (!f) { return; }
    var p = document.createElement("p");
    p.className = "srfRallyCtl";
    p.style.cssText = "margin:12px 0 0;font-size:11.5px;letter-spacing:.02em;" +
                      "color:var(--muted,#7fa8ab);";
    p.appendChild(document.createTextNode("Background rally — swipe, drag or scroll: "));
    ["off", "silent", "sound"].forEach(function(k, i){
      if (i) { p.appendChild(document.createTextNode(" · ")); }
      var b = document.createElement("button");
      b.type = "button";
      b.textContent = k;
      b.setAttribute("data-rl", k);
      b.title = k === "off" ? "no ball, no canvas, no listeners"
              : k === "silent" ? "the ball plays, silently"
              : "add the racket impact and the bounce";
      b.style.cssText = "font:inherit;background:none;border:0;padding:0 1px;" +
                        "cursor:pointer;color:inherit;";
      b.addEventListener("click", function(){ window.srfRallySet(k); });
      p.appendChild(b);
    });
    f.appendChild(p);
    foot = p;
  }

  function paintFoot(){
    if (!foot) { return; }
    var cur = get(), bs = foot.querySelectorAll("button[data-rl]"), i, on;
    for (i = 0; i < bs.length; i++){
      on = bs[i].getAttribute("data-rl") === cur;
      bs[i].setAttribute("aria-pressed", String(on));
      bs[i].style.color = on ? "var(--accent,#9ebaab)" : "inherit";
      bs[i].style.fontWeight = on ? "600" : "400";
    }
  }

  function paint(){ paintSeg(); paintFoot(); }

  window.srfRallySet = function(v){
    put((v === "off" || v === "silent" || v === "sound") ? v : DEF);
    paint();
    sync();
    /* switching to "sound" IS the user gesture iOS wants, so serve one ball as
       the confirmation — you hear what you just turned on. */
    if (get() === "sound" && mounted){
      V.serve({ dx: 300, dy: 60, ms: 150, kind: "swipe" });
    }
  };

  /* --- the app only: leaving the landing page tears it down --------------- */
  if (APP && typeof window.setMode === "function"){
    var _setMode = window.setMode;
    window.setMode = function(){
      var r = _setMode.apply(this, arguments);
      try { sync(); } catch(e){}
      return r;
    };
  }

  /* --- the app only: the net line follows the palette --------------------- */
  if (typeof window.applyTheme === "function"){
    var _applyTheme = window.applyTheme;
    window.applyTheme = function(){
      var r = _applyTheme.apply(this, arguments);
      try { V.repaintAccent(); } catch(e){}
      return r;
    };
  }

  if (!APP) { buildFoot(); }
  paint();
  try { sync(); } catch(e){}
})();
